cart_add:
    path: /cart
    controller: App\MyTheresaCart\Application\Controller\CartController::add
    methods: POST

cart_list:
    path: /cart
    controller: App\MyTheresaCart\Application\Controller\CartController::list
    methods: GET|HEAD
