cart_add:
    path: /cart/product/add
    controller: App\MyTheresaCart\Application\Controller\CartController::add
    methods: PUT

cart_list:
    path: /cart/product
    controller: App\MyTheresaCart\Application\Controller\CartController::list
    methods: GET

user_signin:
    path: /user/signin
    controller: App\MyTheresaCart\Application\Controller\UserController::signin
    methods: POST